# Generated by Django 4.1 on 2022-08-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(verbose_name='Numero')),
                ('chapter_title', models.CharField(max_length=80, verbose_name='Titulo')),
                ('chapter_content', models.TextField()),
                ('chapter_visible', models.BooleanField(default=False)),
                ('chapter_novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='Novel')),
            ],
        ),
    ]
