# Generated by Django 4.1 on 2022-08-13 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
