# Generated by Django 4.1 on 2022-08-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_remove_novel_novel_categories_novel_novel_categories'),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='Novel'),
        ),
    ]
