# Generated by Django 4.1 on 2022-08-05 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_title', models.CharField(max_length=100, verbose_name='Title')),
                ('novel_author', models.CharField(max_length=80, verbose_name='Author')),
                ('novel_status', models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], max_length=9, null=True, verbose_name='Status')),
                ('novel_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated')),
                ('novel_visible', models.BooleanField(default=False, verbose_name='Visible')),
            ],
        ),
    ]
