# Generated by Django 4.1 on 2022-08-04 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_title', models.CharField(max_length=100, verbose_name='Title')),
                ('novel_status', models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], max_length=9, null=True, verbose_name='Status')),
                ('novel_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated')),
                ('novel_visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('novel_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
