# Generated by Django 4.1 on 2022-08-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='novel_categories',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
