# Generated by Django 4.1 on 2022-08-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_author',
            field=models.CharField(max_length=80, verbose_name='Author'),
        ),
    ]
