# Generated by Django 4.1 on 2022-08-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('novels', '0002_novel_novel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_categories',
            field=models.ManyToManyField(related_name='generos', to='categories.category'),
        ),
    ]
