# Generated by Django 4.1 on 2022-08-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_category_category_category_name'),
        ('novels', '0002_alter_novel_novel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='novel_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
        ),
    ]
