# Generated by Django 4.1 on 2022-08-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_category_category_category_name'),
        ('novels', '0003_novel_novel_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='novel_categories',
        ),
        migrations.AddField(
            model_name='novel',
            name='novel_categories',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
