# Generated by Django 4.1 on 2022-08-13 21:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_alter_novel_novel_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='novel_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[200, 400], upload_to='media/%Y/%m/%d'),
        ),
    ]
